# Generated by Django 4.2.7 on 2023-11-06 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchCountry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('un', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('area', models.PositiveBigIntegerField()),
                ('pop2005', models.PositiveBigIntegerField()),
                ('region', models.PositiveSmallIntegerField()),
                ('subregion', models.PositiveSmallIntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
